title: <p align="center"> Sarvesh Upadhyay </p>
logo: /assets/img/logo.png
description: I am working as a Android developer. But now i started my journey to become a AI & ML developer. 
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
