title: <p align="center"> Sarvesh Upadhyay </p>
logo: /assets/img/logo.png
description: I have total 10 years experience currently i am working as Android developer. I just started new course of AI & ML from IIITB .  
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
